server:
  port: 8080

spring:
  application:
    name: servicio-reservas
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tickets}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}

# Configuración de los Chaos Monkeys (Parte A)
resilience4j:
  circuitbreaker:
    instances:
      inventarioCB:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  timelimiter:
    instances:
      pagosTimeout:
        timeout-duration: 3s